name: Download Artifact
description: Downloads an Artifact form a specific Workflow Run

inputs:
  workflow_run_id:
    description: ID of the target Workflow Run
    required: true
  artifact-name:
    description: Name of the Artifact to download
    required: true

runs:
  using: "composite"
  steps:
    - name: "Download"
      uses: actions/github-script@v6
      with:
        script: |
          let artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id,
          });
          let artifact = artifacts.data.artifacts.filter((artifact) => {
            return artifact.name == '${{ inputs.artifact-name }}'
          })[0];
          let download = await github.rest.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: artifact.id,
              archive_format: 'zip',
          });
          let fs = require('fs');
          fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/${{inputs.artifact-name}}.zip`, Buffer.from(download.data));
    - name: "Unzip"
      run: unzip ${{inputs.artifact-name}}.zip
      shell: bash
