name: CI Build

on:
  push: { }
  pull_request:
    branches: [ "master" ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare Java
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
      - name: Prepare Google Services
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
        run: echo $GOOGLE_SERVICES > app/google-services.json
      - name: Prepare Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew assembleDevelopmentDebug
      - name: Unit Tests
        run: ./gradlew testDevelopmentDebugUnitTest
      - name: Unit Test Summary
        uses: test-summary/action@v2
        if: always()
        with:
          paths: app/build/test-results/testDevelopmentDebugUnitTest/TEST-*.xml
      - name: Upload Unit Test Results for Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: unit-test-results
          path: app/build/test-results/testDevelopmentDebugUnitTest/TEST-*.xml
      - name: Lint
        run: ./gradlew lintDevelopmentDebug
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: "Development Debug APK"
          path: app/build/outputs/apk/development/debug/*.apk
  instrumentation-test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare Java
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
      - name: Prepare Gradle
        uses: gradle/gradle-build-action@v2
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          script: ./gradlew spoonDevelopmentDebugAndroidTest
      - name: Instrumentation Test Summary
        uses: test-summary/action@v2
        if: always()
        with:
          paths: "app/build/spoon/junit-reports/*.xml"
      - name: Upload Instrumentation Test Results for Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: instrumentation-test-results
          path: app/build/spoon
