name: Report Instrumentation Test Results

on:
  workflow_run:
    workflows: ["Instrumentation Test"]
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Instrumentation Test Report
        uses: dorny/test-reporter@v1
        with:
          artifact: instrumentation-test-results
          name: Instrumentation Test Report
          path: test_result_*.xml
          reporter: java-junit
