name: Report Unit Test Results

on:
  workflow_run:
    workflows: ["CI Build"]
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Download Unit Test Results # see https://github.com/dorny/test-reporter/issues/363
        uses: actions/download-artifact@v4 # https://github.com/dorny/test-reporter/issues/363
        with:
          name: unit-test-results
          run-id: ${{ github.event.workflow_run.id }}
      - name: Checkout Code for Annotations
        uses: actions/checkout@v4
      - name: Unit Test Report
        uses: dorny/test-reporter@v1
        with:
          name: Unit Test Report
          path: TEST-*.xml
          reporter: java-junit
